# 행렬의 도입 {#matrix}


## 일차연립방정식

다음과 같이 $n$ 개의 변수 $x_1,x_2,\dots,x_n$ 에 대한 $m$ 개의 일차 방정식이 있다면 이를 일차연립방정식(a system of linear equations) 이라고 한다.

$$
\begin{aligned}
a_{11} x_1 + a_{12} x_2 + \dots + a_{1n} x_n & = y_1 \\ 
a_{21} x_1 + a_{22} x_2 + \dots + a_{2n} x_n & = y_2 \\ 
... & \\ 
a_{m1} x_1 + a_{m2} x_2 + \dots + a_{mn} x_n & = y_m 
\end{aligned}
$$ {#eq-syseq}


위의 일차연립방정식(@eq-syseq) 에 사용된 변수  $x_1,x_2,\dots,x_n$ 와 계수 $a_{ij}$, $y_i$ 으로 좀 더 보기 좋고 효율적으로 표현하기 위하여 행렬 $\pmb A$ 와 벡터 $\pmb x$, $\pmb y$ 를 다음과 같이 표기하여

$$
\pmb A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}, 
\quad
\pmb x = 
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
,\quad
\pmb y =
\begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_m
\end{bmatrix}
$$

@eq-syseq 의 일차연립방정식을 다음과 같이 표현할 수 있다.

$$
{\pmb A} {\pmb x} = {\pmb y}, \text{ 즉} \quad 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_m
\end{bmatrix}
$$ {#eq-syseq2}

@eq-syseq2 은 $y_i$의 값을 계산하는 방법이 벡터 $\pmb x$ 의 변수 $x_1,x_2,\dots,x_n$ 와 행렬 $\pmb A$ 의 $i$ 번째 행에 있는 계수들 $a_{i1}, a_{i2}, \dots a_{in}$ 을 다음과 같은 식으로 계산한다는 의미이다. 즉 일차연립방정식(@eq-syseq) 을 행렬 $\pmb A$ 와 벡터 $\pmb x$, $\pmb y$ 로 표현한 것이다.

$$ \sum_{i=j}^n a_{ij} x_j = y_i, \quad i=1,2,\dots,m $$

이제 위에서 일차연립방정식을 표현할 때 사용한 벡터와 행렬의 정의와 기본 연산에 대하여 알아보자. 

## 행렬과 벡터 

### 행렬

$m$ 개의 행과 $n$ 개의 열을 가진, 즉 $m \times n$ 행렬은 보통 알파벳 대문자(upper case letter)로 표현하며 다음과 같은 형태로 나타낸다.

$$
\pmb A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
=(a_{ij})~ (i=1,2,\dots,m; j=1,2,\dots,n)
$$

행렬 $\pmb A$ 가 $m$ 개의 행과 $n$ 개의 열을 가진
 행렬이라면 다음과 같이 표시한다.
 
$$  \pmb A \in \RR^{m \times n} $$


### 벡터

벡터(vector)는 일반적인 행렬의 하나의 행 또는 하나의 열을 나타내는 이름으로 사용된다.

- 행렬의 각 행은 $1 \times n$ 행렬 혹은 행벡터 (row vector)라고 한다. 
- 행렬의 각 열은 $m \times 1$ 행렬 혹은 열벡터 (column vector)라고 한다. 

벡터는 다음과 같이 숫자를 모아 놓은 형태에 따라서 행벡터($\pmb r$)와 열벡터($\pmb c$)로 구분할 수 있다. 

$$
\pmb r = 
\begin{bmatrix}
1~ 2 ~3 ~4~
\end{bmatrix}
,\quad
\pmb c = 
\begin{bmatrix}
1 \\
2 \\
3 \\
4
\end{bmatrix}
$$



또한 벡터는 위치를 나타내는 개체 (geometric vector)로 사용할 수 있다. 위치의 개념을 더 확장하면 벡터는 $n$ 개의 숫자(element)를 순서 있게 모아 놓은 모든 집합, 즉 유클리디안 공간(Euclidean space; $\RR^n$) 을 구성하는 개체로 사용할 수 있다. 


## 중요한 내용과 정의


- 두 행렬이 같다는 정의 

$$ \pmb A = \pmb B  ~~~ \Leftrightarrow ~~~ a_{ij} =b_{ij} ~~~\forall i,j $$

- 정방행렬(square matrix)
- 대각행렬(diagonal matrix)
- 상삼각 행렬(upper triangular matrix)과 하삼각행렬(lower triangular matrix)
- 영행렬(zero matrix)
- 단위행렬(identity matrix)
- 대칭행렬(symmetric matrix)
- 스칼라(scalar)
