# 벡터공간 {#vector_space}

::: callout-note
강의자료 슬라이드 2-5번(군, 필드의 정의)은 강의 범위에 포함되지 않습니다.

부교재 37-40 페이지를 공부하세요.
:::

## 벡터공간의 정의와 의미 


**벡터공간(vector space)** 은 어떤 집합 $S$ 에 다음과 같은 두 개의 연산이 정의된 공간을 말한다.


1. 두 개의 원소에 대한 더하기(addition, $+$) 연산의 정의되어 있다.

    $$+ ~ ~ : S + S \rightarrow  S$$ {#eq-vectorspace-def-1}
    
2. 하나의 실수와  한 개의 원소에 대한 스칼라곱(scalar product, $\cdot$) 연산이 정의되어 있다.

    $$\cdot ~ ~ : \RR \cdot S \rightarrow  S$$ {#eq-vectorspace-def-2}


위에서 **더하기 연산이 정의되어 있다**는 의미는 다음에 주어진 규칙이 성립한다는 의미이다.

- 집합 $S$ 가 연산에 대하여 닫혀있다 (closure).

$$  s_1 + b \in S \quad \forall s_1,b \in S $$

- 결합법칙이 성립한다 (Associativity).

$$  (s_1 + s_2) + s_3 = s_1 + (s_2 +s_3)  \quad \forall s_1,s_2,s_3 \in S $$

- 항등원이 존재한다 (Neutral element).

$$  s + e = e + s = s \quad \exists e ~~\forall s \in S $$

- 역원이 존재한다 (Inverse element).

$$ s + i = i  + s = 0 \quad \exists i ~~\ \forall s \in S $$


일반적으로 항등원($e$) 는 $0$ 으로 표시하며 역원($i$) 는 $-s$ 로 표시한다. 

- 교환법칙이 성립한다 (Commutativity).

$$  s_1 + s_2 = s_2 + s_1  \quad \forall s_1,s_2 \in S $$

또한 위에서 **스칼라곱 연산이 정의되어 있다**는 의미는 다음에 주어진 규칙이 성립한다는 의미이다.


- 스칼라곱 연산의 분배법칙이 성립한다 (Distributivity).


$$  r_1(s_1+s_2) = r_1 s_1 + r_2 s_2,~~~ (r_1+r_2)s = r_1 s + r_2 s  \quad \forall s_1,s_2 \in S, ~~ \forall r_1,r_2 in \RR $$

- 스칼라곱 연산의 결합법칙이 성립한다

$$  r_1(r_2s) = (r_1 r_2) s  \quad \forall s \in S, ~~ \forall r_1,r_2 in \RR $$

- 스칼라곱 연산의 항등원이 존재한다 (Neutral element).

$$  1 \cdot s  = s \quad \forall s \in S $$

일반적으로 벡터공간은 $(S,+,f)$ 라고 표시한다. 이러한 표시에서 함수 $f$ 는 스칼라곱 연산에 대한 정의를 나타내는 것이며 @eq-vectorspace-def-2 에 나타나는 대응을 의미한다.


이 강좌에서는 스칼라로 실수만 사용하고 있으므로 벡터공간을 실벡터(real vector space) 라고 부른다. 

$$ f : \RR \cdot S \rightarrow  S, \quad \text{즉} \quad f(rs) = r \cdot s =rs $$ 

::: {.callout-caution}

벡터 공간에서 주의할 점은 **두 벡터의 곱하기** 가 정의되어 있다는 것이 아니라 하나의 스칼라와 하나의 벡터에 대한 스칼라 곱하기가 정의되어 있다는 것이다.

$$
\begin{bmatrix}
1 \\
2 
\end{bmatrix}
\cdot
\begin{bmatrix}
3 \\
4 
\end{bmatrix}
=?
\quad {but} \quad
3 \cdot
\begin{bmatrix}
1 \\
2 
\end{bmatrix}
= 
\begin{bmatrix}
3 \\
6
\end{bmatrix}
$$

**두 벡터의 곱하기** 는 나중에 내적(inner product) 란 이름으로 따로 정의한다.

:::


## 중요한 내용과 정의

- 벡터공간의 예제 (슬라이드 참조)
- 부분공간(subspace)의 정의와 예제(부교재 39 페이지 Example 2.12 참조)



