# 행렬의 계수 {#matrix_rank}


## 계수의 정의

::: {#def-rank}

## 계수의 정의

행렬의 계수(rank)란 **행렬의 일차 독립인 행들의 최대 수** 또는 **일차독립인 열들의 최대 수**로 정의된다

$$ rank(\pmb A) = rk(\pmb A) = dim(Col(\pmb A)) = dim(Row(\pmb A)) $$
$\blacksquare$

:::


꼭 기억해야 할 것은 행렬의 계수는 열들을 이용하여 구한 계수와 행들을 이용하여 구한 계수가 같다는 것이다. 즉, 행렬의 계수는 열의 계수와 행의 계수 중 하나만 구해도 된다는 것이다.

## 중요공식

- $rank(\pmb A ) = rank(\pmb A^T)$

- 행렬 $\pmb A \in \RR^n$ 가 정방행렬이고 계수가 $n$ 이면 역행렬이 존재한다. 약행렬이 존재하면 정칙행렬(non-sigular matrix)이라고 한다.

- 더 나아가 다음에 나오는 문장은 모두 동치(equaivalent)이다.

    모든 $\pmb A \in \RR^{n \times n}$ 에 대하여 

    $\pmb A$ 가 정칙행렬이다.
    
    $\quad \Leftrightarrow$  $\pmb A$ 의 열들이 일차독립이다.
    
    $\quad \Leftrightarrow$  $\pmb A$ 의 행들이 일차독립이다.
    
    $\quad \Leftrightarrow$  $\pmb A$ 의 계수가 $n$ 이다.
    
    $\quad \Leftrightarrow$  $\pmb A$ 의 기약행사다리꼴행렬이 항등행렬이다.
    
    $\quad \Leftrightarrow$  $\pmb A \pmb x = \pmb 0$ 해는 영벡터가 유일하다.

- 최대계수행렬

  + $\pmb A \in \RR^{n \times n}$ 에 대하여 $m \le n$ 이고 $rank(\pmb A) = m$이면 $\pmb A$ 는 최대 행계수를 갖는다. 이 때 $\pmb A$를  최대 행계수 행렬(full row rank matrix)이라고한다.
  
  + $\pmb A \in \RR^{n \times n}$ 에 대하여 $m \le n$ 이고 $m \ge n$이고 $rank(\pmb A) = n$ 이면 $\pmb A$는 최대 열계수를 갖는다 A는 최대 열계수 행렬이다라고 한다.이 때 $\pmb A$를 최대 열계수행렬((full column rank matrix)이라고 한다.
  
  + $\pmb A$ 가 최대 행계수 행렬 또는 최대 열계수 행렬인 경우 $\pmb A$ 는 최대 계수를 갖는다 또는 $\pmb A$ 는 최대 계수 행렬(full rank matrix) 이라고 한다.
  
  
## 예제 


### 부교재

  - Example 2.18 (Rank) 
  
  
### 연습문제 1

다음과 같은 $3 \times 4$ 행렬에 행연산을 적용하여 행사다리꼴 행렬로 만들어 보자.

$$
\pmb A =
\begin{bmatrix}
1 & 2 & 1 & 5\\
2 & 5 & 1 & 14 \\
4 & 9 & 3 & 24
\end{bmatrix}
$$ {#eq-matrix-9-1}

$$
\begin{aligned}
&
\begin{bmatrix}
1 & 2 & 1 & 5\\
2 & 5 & 1 & 14 \\
4 & 9 & 3 & 24
\end{bmatrix}
\begin{array}{c}
\\
(-2)(\text{1st row}) + (\text{2nd row}) 
\\
\end{array} \\
& \\
\rightarrow
& 
\begin{bmatrix}
1 & 2 & 1 & 5\\
0 & 1 & -1 & 4 \\
4 & 9 & 3 & 24
\end{bmatrix}
\begin{array}{c}
\\
\\
 (-4)(\text{1st row}) + (\text{3rd row}) 
\end{array} \\
& \\
\rightarrow
& 
\begin{bmatrix}
1 & 2 & 1 & 5\\
0 & 1 & -1 & 4 \\
0 & 1 & -1 & 4
\end{bmatrix}
\begin{array}{c}
\\
\\
 (-1) (\text{2nd row}) + (\text{3rd row})  
\end{array} \\
& \\
\rightarrow
&  
\begin{bmatrix}
1 & 2 & 1 & 5\\
0 & 1 & -1 & 4 \\
0 & 0 & 0 & 0
\end{bmatrix}
\end{aligned}
$$


위의 결과에서  피봇 행이 2개가 나타나며 나머지 행은 모두 0으로 나타난다. 이러한 결과를 행렬의 계수가 2인 것을 의미하며($rank(\pmb A)=2$). 계수의 정의에 의하여 선형독립인 행의 갯수가 2이다. 

따라서 마지막 행은 다른 2개의 행들의 선형조합이고 행연산의 결과로 모든 원소가 0이 되는 것을 알 수 있다. 

만약 @eq-matrix-9-1 에 나타난 행렬의 열들을 고려하면 선형독립인 열들이 2개가 될까? @eq-matrix-9-1 의 행렬 $\pmb A$ 의 전치 행렬은 열들이 행으로 바뀐 행렬이므로 위와 유사하게 행 연산을 적용하면 선향독립인 열의 개수를 구할 수 있다. 

$$
\pmb A^T =
\begin{bmatrix}
1 & 2 & 4 \\
2 & 5 & 9 \\
1 & 1 & 3 \\
5 & 14 & 24
\end{bmatrix}
$$

$$
\begin{aligned}
 & 
\begin{bmatrix}
1 & 2 & 4 \\
2 & 5 & 9 \\
1 & 1 & 3 \\
5 & 14 & 24
\end{bmatrix}
\begin{array}{c}
\\
(\text{change 1st row and 3rd row}) 
\\
\end{array} \\
 \\
 \rightarrow & 
\begin{bmatrix}
1 & 1 & 3 \\
2 & 5 & 9 \\
1 & 2 & 4 \\
5 & 14 & 24
\end{bmatrix}
\begin{array}{c}
\\
(-2)(\text{1st row}) + (\text{2nd row}) \\
(-1)(\text{1st row}) + (\text{3rd row}) \\
(-5)(\text{1st row}) + (\text{4th row}) 
\end{array} \\
 \rightarrow & 
\begin{bmatrix}
1 & 1 & 3 \\
0 & 3 & 3 \\
0 & 1 & 1 \\
0 & 9 & 9
\end{bmatrix}
\begin{array}{c}
\\
\\
(\text{change 2nd row and 3rd row}) \\
\\
\end{array} \\
 \rightarrow & 
\begin{bmatrix}
1 & 1 & 3 \\
0 & 1 & 1 \\
0 & 3 & 3 \\
0 & 9 & 9
\end{bmatrix}
\begin{array}{c}
\\
(-1)(\text{2nd row}) + (\text{3rd row}) \\
(-3)(\text{2nd row}) + (\text{4th row}) 
\\
\end{array} \\
 \rightarrow & 
\begin{bmatrix}
1 & 1 & 3 \\
0 & 1 & 1 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
\end{aligned}
$$
위와 같이  4개의 열로 보아도 서로 독립인 열의 개수는 2개임을 알 수 있다. 

따라서 행렬의 계수를 구하는 경우는 행을 이용한 연산과 열을 이용한 연산 중 하나만 선택하여 계산하면 된다.  


<!----

이제 교과서 87페이지에 나타난 행렬의 계수를 구해보자.
\[ 
\pmb A =
\begin{bmatrix}[r]
1 & 1 & 3\\
1 & 1 & 3 \\
4 & 4 & 12 \\
2 & 2 & 5
\end{bmatrix}
\]

행렬의 계수는 전치 행렬의 계수와 같으므로 ($r(\pmb A) = r(\pmb A^t)$) 전치행렬을 고려해도 무방하다.

\[ 
\pmb A^t =
\begin{bmatrix}[r]
1 & 1 & 4 & 2\\
1 & 1 & 4 & 2 \\
3 & 3 & 12 & 5
\end{bmatrix}
\]

행(열)의 교환은 기본치환행렬을 행렬의 앞(뒤)에 곱하는 것과 같다. 정칙행렬을 앞 또는 뒤에 곱해도 행렬의 계수가 변하지 않으므로 행렬의 두 행(또는 열)을 교환하여도 행렬의 계수는 변하지 않는다

이제 $\pmb A^t$의 2행과 3행을 바꾸고 다시 2열과 4열을 바꾸어 보자.

\[
\pmb E_{23} \pmb A^t \pmb E_{24} =
\begin{bmatrix}[r]
1 & 2 & 4 & 1\\
3 & 5 & 12 & 3 \\
1 & 2 & 4 & 1 
\end{bmatrix}
\]

위의 행렬에 대각원소 아래를 0으로 바꾸는 행연산을 적용해 보자.

\begin{aligned}
\pmb E_{23} \pmb A^t \pmb E_{24} =
\begin{bmatrix}[r]
1 & 2 & 4 & 1\\
3 & 5 & 12 & 3 \\
1 & 2 & 4 & 1 
\end{bmatrix}
&
\\
(-3)(\text{1st row}) + (\text{2nd row}) \rightarrow&
\begin{bmatrix}[r]
1 & 2 & 4 & 1\\
0 & -1 & 0 & 0 \\
1 & 2 & 4 & 1 
\end{bmatrix}
\\
 (-1)(\text{1st row}) + (\text{3rd row}) \rightarrow&
\begin{bmatrix}[r]
\tikzmarkin{c3}(0.1,-0.1)(-0.1,0.35) 1 \tikzmarkend{c3}& 2 & 4 & 1\\
0 & \tikzmarkin{c4}(0.1,-0.1)(-0.1,0.35)-1 \tikzmarkend{c4}& 0 & 0 \\
0 & 0 & 0 & 0 
\end{bmatrix}
\end{aligned}

위의 결과에서 3개의 대각 원소 중에서 0이 아닌 대각원소가 2개가 나타나며 나머지 행은 모두 0으로 나타난다. 이러한 결과를 행렬의 계수가 2인 것을 의미한다. 


--->

  