# 행렬식과 대각합 {#trace-det}

::: callout-note
이 노트의 내용은 부교재 100-105쪽의 내용을 요약한 것이다. 
:::


## 용어

- determinant : 행렬식
- trace : 대각합

::: callout-caution

행렬식과 대각합은 정방행렬(square matrix)에 대해서만 정의된다.

:::

## 행렬식

##행렬식의 정의

정방행렬(square matrix) $\pmb A$ 의 행렬식(determinant)는 $\operatorname{det}(\pmb A)$ 로 표기한다.

$A \in \mathbb{R}^{2 \times 2}$ 의 행렬식은 다음과 같이 계산한다.

$$
\operatorname{det}(\boldsymbol{A})=\left|\begin{array}{ll}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{array}\right|=a_{11} a_{22}-a_{12} a_{21} .
$$

### 역행렬과 Rank

- Theorm 4.1. 과 Theorem 4.3 

행렬 $\pmb A$ 가 $n \times n $ 정방행렬(square matrix) 인 경우 다음 3개의 문장이 동치(equivalent)임을 보여준다.

  + $\operatorname{det}(\boldsymbol{A}) \ne 0$
  + $rank(\boldsymbol{A}) = n$
  + $\boldsymbol{A}$은 역행렬이 존재한다 

### 삼각행렬의 행렬식

행렬 $\pmb T$ 가 상삼각행렬(upper triangular matrix) 또는 하삼각행렬(lower triangular matrix)이면 행렬식은 대각원소(diagonal element)의 곱과 같다.

$$
\operatorname{det}(\boldsymbol{T}) = \prod_{i=1}^n T_{ii}
$$

### Laplace Expansion

- 행렬식을 계산하는 방법 중 하나는 Laplace Expansion 이며 Theorem 4.2. 에서 설명한다.
- Example 4.3 꼭 읽어보기



### 행렬식의 성질

$$ 
\operatorname{det}(\boldsymbol{A} \boldsymbol{B}) = \operatorname{det}(\boldsymbol{A}) \operatorname{det}(\boldsymbol{B})
$$
$$ 
\operatorname{det}(\boldsymbol{A}^T) = \operatorname{det}(\boldsymbol{A})
$$



$$ 
\operatorname{det}(\boldsymbol{A}^{-1}) = \frac{1}{\operatorname{det}(\boldsymbol{A})}
$$


$$ 
\operatorname{det}(\lambda \boldsymbol{A}) = \lambda^n \operatorname{det}(\boldsymbol{A})
$$


## 대각합

대각합의 정의는 부교재 식 4.18 에서 정의된다.


### 대각합의 성질

- $\operatorname{tr}(\boldsymbol{A}+\boldsymbol{B})=\operatorname{tr}(\boldsymbol{A})+\operatorname{tr}(\boldsymbol{B})$ for $\boldsymbol{A}, \boldsymbol{B} \in \mathbb{R}^{n \times n}$

- $\operatorname{tr}(\alpha \boldsymbol{A})=\alpha \operatorname{tr}(\boldsymbol{A}), \alpha \in \mathbb{R}$ for $\boldsymbol{A} \in \mathbb{R}^{n \times n}$

- $\operatorname{tr}\left(\boldsymbol{I}_n\right)=n$

- $\operatorname{tr}(\boldsymbol{A B})=\operatorname{tr}(\boldsymbol{B} \boldsymbol{A})$ for $\boldsymbol{A} \in \mathbb{R}^{n \times k}, \boldsymbol{B} \in \mathbb{R}^{k \times n}$

대각합은 교환법칙이 성립히기 떄문에 다음과 같은 성질이 성립한다.

$$
\operatorname{tr}(\boldsymbol{A} \boldsymbol{K} \boldsymbol{L})=\operatorname{tr}(\boldsymbol{K} \boldsymbol{L} \boldsymbol{A})
$$
벡터의 연산에서도 대각합의 교환법칙이 성립디어 다음과 같은 유용한 식이 성립한다.

$$
\operatorname{tr}\left(\boldsymbol{x} \boldsymbol{y}^{\top}\right)=\operatorname{tr}\left(\boldsymbol{y}^{\top} \boldsymbol{x}\right)=\boldsymbol{y}^{\top} \boldsymbol{x} \in \mathbb{R} .
$$

대각합의 교환법칙때문에 어떤 행렬의 앞에 특정 행렬을 곱하고, 뒤에 역행렬을 곱해도 대각합은 변하지 않는다. 

$$
\operatorname{tr}\left(\boldsymbol{S}^{-1} \boldsymbol{A} \boldsymbol{S}\right) = \operatorname{tr}\left(\boldsymbol{A} \boldsymbol{S} \boldsymbol{S}^{-1}\right)=\operatorname{tr}(\boldsymbol{A})
$$

## 특성다항식

특성다항식(Characteristic polynomial)은 다음과 같이 정의된다 (부교재 definition 4.5)

실수 $\lambda \in \mathbb{R}$ 와  정방행렬(square matrix) $\boldsymbol{A} \in \mathbb{R}^{n \times n}$ 에 대하여

$$
\begin{aligned}
p_{\boldsymbol{A}}(\lambda) & :=\operatorname{det}(\boldsymbol{A}-\lambda \boldsymbol{I}) \\
& =c_0+c_1 \lambda+c_2 \lambda^2+\cdots+c_{n-1} \lambda^{n-1}+(-1)^n \lambda^n,
\end{aligned}
$$ {#eq-char-poly}

### 행렬식과 대각합과의 관계


$$ c_0 = \operatorname{det}(\boldsymbol A)$$

$$ c_{n-1} = (-1)^n \operatorname{tr}(\boldsymbol A)$$
